/**
 * Generates the docs rules reference — an index page plus one page per rule —
 * from the single source of truth: the rule definitions in
 * `@docker-doctor/core`, merged with the authored prose in
 * `scripts/rule-page-content.ts`. Run it with:
 *
 *   bun run docs:rules
 *
 * Run by Bun (not the app's `tsc`), so importing core's raw-TS sources is
 * safe here even though the web app cannot import them directly — see the
 * note in `apps/web/lib/score.ts` about core's ES2018 regex named groups
 * versus the web app's ES2017 target. Generation fails if a rule has no
 * authored content (or content references a rule that no longer ships), so
 * the pages can never drift from the rules the CLI actually runs.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { allRules } from "../packages/core/src/rules/index";
import type {
  RuleCategory,
  RuleDefinition,
} from "../packages/core/src/types/index";
import type { RuleExample } from "./rule-page-content";
import { rulePageContent } from "./rule-page-content";

const RULES_DIR = path.join(
  import.meta.dirname,
  "..",
  "apps/web/content/docs/reference/rules"
);

// Section order for the index page and the sidebar. Every category present
// in `allRules` must be listed here; the guard below fails the build if a
// new one is added to core without being placed in the docs.
const CATEGORY_ORDER: readonly RuleCategory[] = [
  "Security",
  "Performance",
  "Best Practices",
  "Compose",
  "Image Size",
];

const CATEGORY_BLURB: Record<RuleCategory, string> = {
  "Best Practices": "General Dockerfile and Compose hygiene.",
  Compose: "Docker Compose-specific checks.",
  "Image Size": "Keeps final images small.",
  Performance: "Reduces build time and layer bloat.",
  Security: "Catches Dockerfile patterns that widen your attack surface.",
};

// Matches the severity prefixes rendered by the CLI's terminal formatter
// (packages/docker-doctor/src/formatters/terminal.ts) so the sample
// diagnostic on each page looks like real scan output.
const SEVERITY_PREFIX: Record<string, string> = {
  error: "✖ ERROR",
  info: "ℹ INFO",
  warning: "⚠ WARN",
};

const AUTOGEN_HEADER =
  "# AUTOGENERATED from @docker-doctor/core by scripts/generate-rules-doc.ts.\n# Do not edit by hand — run `bun run docs:rules` to regenerate.";

const ruleSlug = (rule: RuleDefinition): string =>
  rule.key.replace("docker-doctor/", "");

const rulesByCategory = (category: RuleCategory): RuleDefinition[] =>
  allRules.filter((rule) => rule.category === category);

const assertCoverage = (): void => {
  const knownCategories = new Set<RuleCategory>(CATEGORY_ORDER);
  const missingCategories = [
    ...new Set(allRules.map((rule) => rule.category)),
  ].filter((category) => !knownCategories.has(category));
  if (missingCategories.length > 0) {
    throw new Error(
      `Rule categories missing from CATEGORY_ORDER in scripts/generate-rules-doc.ts: ${missingCategories.join(", ")}. Add them so they appear in the docs.`
    );
  }

  const ruleKeys = new Set(allRules.map((rule) => rule.key));
  const missingContent = allRules
    .filter((rule) => !rulePageContent[rule.key])
    .map((rule) => rule.key);
  if (missingContent.length > 0) {
    throw new Error(
      `Rules missing authored page content in scripts/rule-page-content.ts: ${missingContent.join(", ")}. Every shipped rule needs a docs page.`
    );
  }

  const orphaned = Object.keys(rulePageContent).filter(
    (key) => !ruleKeys.has(key)
  );
  if (orphaned.length > 0) {
    throw new Error(
      `scripts/rule-page-content.ts has content for rules that no longer ship: ${orphaned.join(", ")}. Remove or rename the entries.`
    );
  }
};

const renderExample = (example: RuleExample): string => {
  const meta = example.title ? ` title="${example.title}"` : "";
  return `\`\`\`${example.lang}${meta}\n${example.code}\n\`\`\``;
};

// Core's help strings are written for the terminal, not MDX prose — a lone
// `*` (e.g. in '/var/lib/apt/lists/*') reads as an unmatched emphasis
// marker, and `<package>` / `{ condition: … }` parse as JSX/expressions.
// Escape them up front so generated output compiles and is formatter-clean.
const escapeProse = (text: string): string =>
  text.replaceAll("*", "\\*").replaceAll("<", "\\<").replaceAll("{", "\\{");

const buildRulePage = (rule: RuleDefinition): string => {
  const content = rulePageContent[rule.key];
  const slug = ruleSlug(rule);
  const appliesTo =
    rule.category === "Compose" ? "Docker Compose files" : "Dockerfiles";
  const prefix = SEVERITY_PREFIX[rule.defaultSeverity] ?? rule.defaultSeverity;
  const notes = content.notes ? `\n${content.notes}\n` : "";

  return `---
${AUTOGEN_HEADER}
title: ${slug}
description: >-
  ${content.description}
---

${content.intro}

## What the rule catches

${renderExample(content.bad)}

Scanning this file reports:

\`\`\`text
${prefix} [${rule.key}]
  ${rule.message}
\`\`\`

## Why it matters

${content.why}

## How to fix it

${escapeProse(rule.help)}

${renderExample(content.good)}
${notes}
## Rule details

- **Rule key** — \`${rule.key}\`
- **Category** — ${rule.category}
- **Default severity** — \`${rule.defaultSeverity}\`
- **Applies to** — ${appliesTo}

Explain this rule from the CLI:

\`\`\`bash
npx @docker-doctor/cli@latest rules explain ${rule.key}
\`\`\`

Change its severity — or turn it off — in your [config file](/docs/reference/configuration):

\`\`\`ts
// docker-doctor.config.ts
export default {
  rules: {
    "${rule.key}": "off",
  },
};
\`\`\`

Severity affects the [health score](/docs/reference/scoring): \`error\` findings cost more points than \`warning\`, and \`info\` costs the least.
`;
};

const renderIndexRule = (rule: RuleDefinition): string =>
  `- [\`${ruleSlug(rule)}\`](/docs/reference/rules/${ruleSlug(rule)}) — ${rule.message} (\`${rule.defaultSeverity}\`)`;

const renderIndexSection = (category: RuleCategory): string => {
  const rules = rulesByCategory(category);
  return [
    `## ${category}`,
    "",
    CATEGORY_BLURB[category],
    "",
    ...rules.map(renderIndexRule),
  ].join("\n");
};

const buildIndexPage = (): string => {
  const total = allRules.length;
  const sections = CATEGORY_ORDER.map(renderIndexSection).join("\n\n");

  return `---
${AUTOGEN_HEADER}
title: Rules
description: Every rule docker-doctor ships, grouped by category.
---

docker-doctor ships ${total} rules across ${CATEGORY_ORDER.length} categories. Every diagnostic carries a full rule key (e.g. \`docker-doctor/no-root-user\`) that you can pass to \`rules explain\` or use to tune severity in your config. Each rule below links to a page with failing and fixed examples.

List everything docker-doctor knows about:

\`\`\`bash
npx @docker-doctor/cli@latest rules list
\`\`\`

Explain any single rule in depth:

\`\`\`bash
npx @docker-doctor/cli@latest rules explain <rule>
\`\`\`

${sections}

See [Configuration](/docs/reference/configuration) to change a rule's severity or turn off a whole category.
`;
};

const buildMeta = (): string => {
  const orderedSlugs = CATEGORY_ORDER.flatMap((category) =>
    rulesByCategory(category).map(ruleSlug)
  );
  return `${JSON.stringify({ pages: ["index", ...orderedSlugs], title: "Rules" }, null, 2)}\n`;
};

assertCoverage();
await mkdir(RULES_DIR, { recursive: true });

const expectedFiles = new Set([
  "index.mdx",
  "meta.json",
  ...allRules.map((rule) => `${ruleSlug(rule)}.mdx`),
]);

// Remove pages for rules that no longer exist so deletions in core
// propagate to the site instead of leaving orphaned routes.
const existing = await readdir(RULES_DIR);
await Promise.all(
  existing
    .filter((entry) => !expectedFiles.has(entry))
    .map((entry) => rm(path.join(RULES_DIR, entry)))
);

await Promise.all([
  writeFile(path.join(RULES_DIR, "index.mdx"), buildIndexPage(), "utf-8"),
  writeFile(path.join(RULES_DIR, "meta.json"), buildMeta(), "utf-8"),
  ...allRules.map((rule) =>
    writeFile(
      path.join(RULES_DIR, `${ruleSlug(rule)}.mdx`),
      buildRulePage(rule),
      "utf-8"
    )
  ),
]);

process.stdout.write(
  `Generated ${allRules.length} rule pages + index in ${RULES_DIR}\n`
);
