/**
 * Generates the docs "Rules" reference page from the single source of truth:
 * the rule definitions in `@docker-doctor/core`. Run it with:
 *
 *   bun run docs:rules
 *
 * Run by Bun (not the app's `tsc`), so importing core's raw-TS sources is
 * safe here even though the web app cannot import them directly — see the
 * note in `apps/web/lib/score.ts` about core's ES2018 regex named groups
 * versus the web app's ES2017 target. Keeping the page generated means it
 * can never drift from the rules the CLI actually ships.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import { allRules } from "../packages/core/src/rules/index";
import type {
  RuleCategory,
  RuleDefinition,
} from "../packages/core/src/types/index";

const OUTPUT = path.join(
  import.meta.dirname,
  "..",
  "apps/web/content/docs/reference/rules.mdx"
);

// Section order for the page. Every category present in `allRules` must be
// listed here; the guard below fails the build if a new one is added to core
// without being placed in the docs.
const CATEGORY_ORDER: readonly RuleCategory[] = [
  "Security",
  "Performance",
  "Best Practices",
  "Compose",
  "Image Size",
];

const CATEGORY_BLURB: Record<RuleCategory, string> = {
  "Best Practices": "General Dockerfile and Compose hygiene.",
  Compose: "Docker Compose-specific checks.",
  "Image Size": "Keeps final images small.",
  Performance: "Reduces build time and layer bloat.",
  Security: "Catches Dockerfile patterns that widen your attack surface.",
};

const rulesByCategory = (category: RuleCategory): RuleDefinition[] =>
  allRules.filter((rule) => rule.category === category);

const renderRule = (rule: RuleDefinition): string =>
  `- \`${rule.key}\` — ${rule.message} _(${rule.defaultSeverity})_`;

const renderSection = (category: RuleCategory): string => {
  const rules = rulesByCategory(category);
  return [
    `## ${category}`,
    "",
    CATEGORY_BLURB[category],
    "",
    ...rules.map(renderRule),
  ].join("\n");
};

const assertEveryCategoryCovered = (): void => {
  const known = new Set<RuleCategory>(CATEGORY_ORDER);
  const missing = [...new Set(allRules.map((rule) => rule.category))].filter(
    (category) => !known.has(category)
  );
  if (missing.length > 0) {
    throw new Error(
      `Rule categories missing from CATEGORY_ORDER in scripts/generate-rules-doc.ts: ${missing.join(", ")}. Add them so they appear in the docs.`
    );
  }
};

const build = (): string => {
  assertEveryCategoryCovered();

  const total = allRules.length;
  const sections = CATEGORY_ORDER.map(renderSection).join("\n\n");

  return `---
# AUTOGENERATED from @docker-doctor/core by scripts/generate-rules-doc.ts.
# Do not edit by hand — run \`bun run docs:rules\` to regenerate.
title: Rules
description: Every rule docker-doctor ships, grouped by category.
---

docker-doctor ships ${total} rules across ${CATEGORY_ORDER.length} categories. Every diagnostic carries a full rule key (e.g. \`docker-doctor/no-root-user\`) that you can pass to \`rules explain\` or use to tune severity in your config.

List everything docker-doctor knows about:

\`\`\`bash
npx @docker-doctor/cli@latest rules list
\`\`\`

Explain any single rule in depth:

\`\`\`bash
npx @docker-doctor/cli@latest rules explain <rule>
\`\`\`

${sections}

See [Configuration](/docs/reference/configuration) to change a rule's severity or turn off a whole category.
`;
};

const content = build();
await writeFile(OUTPUT, content, "utf-8");
process.stdout.write(
  `Generated ${OUTPUT} (${allRules.length} rules across ${CATEGORY_ORDER.length} categories)\n`
);
